"use client";
import { useQuery } from "@tanstack/react-query";
import { FolderKanban, Settings, Users } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { PageHeader } from "@/components/layout/page-header";
import { ResourceStatusBadge } from "@/components/resources/resource-status-badge";
import { Button } from "@/components/ui/button";
type Detail = { name: string; members: { userId: string; name: string; email: string }[]; projects: { id: string; name: string; slug: string; status: string }[] };
export default function TeamDetailPage() { const { orgSlug, teamSlug } = useParams<{ orgSlug: string; teamSlug: string }>(); const router = useRouter(); const { data, isLoading, isError } = useQuery<Detail>({ queryKey: ["org", orgSlug, "team", teamSlug], queryFn: async () => { const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL ?? ""}/organizations/${orgSlug}/teams/${teamSlug}`, { credentials: "include" }); if (!response.ok) throw new Error("Team konnte nicht geladen werden."); return response.json(); } }); const base = `/${orgSlug}/teams/${teamSlug}`; return <div className="space-y-6 p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><PageHeader title={data?.name ?? "Team"} description="Arbeitsgruppe innerhalb dieser Organisation." /><Button variant="outline" onClick={() => router.push(`${base}/settings`)}><Settings className="size-4" /> Einstellungen</Button></div>{isError ? <p className="rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-100">Team konnte nicht geladen werden.</p> : null}{isLoading ? <p className="text-sm text-zinc-500">Team wird geladen …</p> : null}{data ? <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border border-white/[0.07] bg-[#172128] p-5"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold text-zinc-100"><Users className="size-4 text-[#81ecec]" /> Mitglieder</h2><Button size="sm" variant="ghost" onClick={() => router.push(`${base}/members`)}>Verwalten</Button></div><div className="mt-4 space-y-3">{data.members.slice(0, 4).map((item) => <div key={item.userId}><p className="text-sm text-zinc-200">{item.name}</p><p className="text-xs text-zinc-500">{item.email}</p></div>)}{!data.members.length ? <p className="text-sm text-zinc-500">Keine Mitglieder.</p> : null}</div></section><section className="rounded-2xl border border-white/[0.07] bg-[#172128] p-5"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold text-zinc-100"><FolderKanban className="size-4 text-[#81ecec]" /> Projekte</h2><Button size="sm" variant="ghost" onClick={() => router.push(`${base}/projects`)}>Verwalten</Button></div><div className="mt-4 space-y-3">{data.projects.slice(0, 4).map((item) => <div key={item.id} className="flex items-center gap-2"><div className="min-w-0 flex-1"><p className="text-sm text-zinc-200">{item.name}</p><p className="text-xs text-zinc-500">{item.slug}</p></div><ResourceStatusBadge status={item.status} /></div>)}{!data.projects.length ? <p className="text-sm text-zinc-500">Keine Projekte zugewiesen.</p> : null}</div></section></div> : null}</div>; }
