providers:
  docker:
    exposedByDefault: false
  file:
    # Verweist auf das Verzeichnis, in dem deine Steuerungsebene (Control Plane)
    # die dynamischen Konfigurationen für die Firecracker-VMs ablegt.
    directory: "/etc/traefik/dynamic"
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

# Zertifikats-Manager für die automatische SSL-Ausstellung externer Kunden-Domains
certificatesResolvers:
  le-kunden:
    acme:
      email: "admin@devion.local"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web