"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
type Team = { id: string; name: string };
type Access = { accessMode: "organization" | "team"; teams: Team[] };
type Project = { permissions: string[] };
const api = (path: string) => `${process.env.NEXT_PUBLIC_API_URL ?? ""}${path}`;
export default function ProjectSettingsAccessPage() {
  const { orgSlug, projectId } = useParams<{ orgSlug: string; projectId: string }>(); const client = useQueryClient(); const [mode, setMode] = useState<Access["accessMode"]>("organization"); const [teamIds, setTeamIds] = useState<string[]>([]);
  const access = useQuery<Access>({ queryKey: ["orgs", orgSlug, "projects", projectId, "access"], queryFn: async () => { const response = await fetch(api(`/organizations/${orgSlug}/projects/${projectId}/teams`), { credentials: "include" }); if (!response.ok) throw new Error("Zugriff konnte nicht geladen werden"); return response.json(); } });
  const project = useQuery<Project>({ queryKey: ["orgs", orgSlug, "projects", projectId], queryFn: async () => { const response = await fetch(api(`/organizations/${orgSlug}/projects/${projectId}`), { credentials: "include" }); if (!response.ok) throw new Error("Projekt konnte nicht geladen werden"); return response.json(); } });
  const teams = useQuery<Team[]>({ queryKey: ["orgs", orgSlug, "teams"], queryFn: async () => { const response = await fetch(api(`/organizations/${orgSlug}/teams`), { credentials: "include" }); if (!response.ok) throw new Error("Teams konnten nicht geladen werden"); return response.json(); } });
  useEffect(() => { if (access.data) { setMode(access.data.accessMode); setTeamIds(access.data.teams.map((team) => team.id)); } }, [access.data]);
  const save = useMutation({ mutationFn: async () => { const response = await fetch(api(`/organizations/${orgSlug}/projects/${projectId}/access`), { method: "PUT", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ accessMode: mode, teamIds }) }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.error ?? "Zugriff konnte nicht gespeichert werden"); }, onSuccess: () => void client.invalidateQueries({ queryKey: ["orgs", orgSlug, "projects", projectId] }) });
  const canManage = project.data?.permissions.includes("projects.manage_access") ?? false;
  return <div className="space-y-6 p-6"><PageHeader title="Zugriff" description="Organisationweite Projects stehen allen berechtigten Mitgliedern offen; Team-Projects nur zugewiesenen Teams." />{access.isLoading || teams.isLoading || project.isLoading ? <p className="text-sm text-zinc-500">Zugriff wird geladen …</p> : <section className="space-y-5 rounded-2xl border border-white/[0.07] bg-[#172128] p-5"><div className="flex gap-5 text-sm text-zinc-200"><label><input disabled={!canManage} type="radio" checked={mode === "organization"} onChange={() => setMode("organization")} /> Ganze Organisation</label><label><input disabled={!canManage} type="radio" checked={mode === "team"} onChange={() => setMode("team")} /> Teams</label></div>{mode === "team" ? <div className="space-y-2 border-t border-white/[0.06] pt-4">{(teams.data ?? []).map((team) => <label key={team.id} className="flex items-center gap-2 text-sm text-zinc-300"><input disabled={!canManage} type="checkbox" checked={teamIds.includes(team.id)} onChange={(event) => setTeamIds((current) => event.target.checked ? [...current, team.id] : current.filter((id) => id !== team.id))} />{team.name}</label>)}{!teams.data?.length ? <p className="text-sm text-zinc-500">Noch keine Teams verfügbar.</p> : null}</div> : null}{save.error ? <p role="alert" className="text-sm text-red-300">{save.error.message}</p> : null}{canManage ? <div className="flex justify-end"><Button onClick={() => save.mutate()} disabled={save.isPending || (mode === "team" && !teamIds.length)}>{save.isPending ? "Speichere …" : "Zugriff speichern"}</Button></div> : <p className="text-sm text-zinc-500">Du hast keine Berechtigung, den Project-Zugriff zu verwalten.</p>}</section>}</div>;
}
