import { auditLogs, db, environmentVariables, projectEnvironments } from "@repo/db";
import { and, asc, count, eq, inArray } from "drizzle-orm";
import { Hono } from "hono";
import { z } from "zod";
import { requireAuthenticatedUser } from "../middleware/auth.js";
import { resolveProjectAccess } from "../features/projects/access.js";
import { decryptEnvironmentValue, encryptEnvironmentValue } from "../features/environments/crypto.js";
import type { AppEnv } from "../types/env.js";

const routes = new Hono<AppEnv>();
routes.use("/*", requireAuthenticatedUser);
const environmentInput = z.object({ name: z.string().trim().regex(/^[a-z][a-z0-9-]{0,62}$/), displayName: z.string().trim().min(1).max(80), branch: z.string().trim().min(1).max(255).default("main"), autoDeployEnabled: z.boolean().default(false), protected: z.boolean().default(false) });
const environmentUpdate = environmentInput.partial().refine((value) => Object.keys(value).length > 0);
const variableInput = z.object({ key: z.string().trim().regex(/^[A-Z_][A-Z0-9_]{0,127}$/), value: z.string().max(16_384), isSecret: z.boolean().default(false) });

async function scope(request: Request, slug: string, projectId: string, permission: "projects.read" | "projects.manage_environments" = "projects.read") { return resolveProjectAccess(request, slug, projectId, permission); }
async function environmentInScope(projectId: string, environmentId: string) { return db.query.projectEnvironments.findFirst({ where: and(eq(projectEnvironments.id, environmentId), eq(projectEnvironments.projectId, projectId)) }); }

routes.get("/:orgSlug/projects/:projectId/environments", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId")); if (!access) return c.json({ error: "Project not found or access denied" }, 404); const items = await db.select().from(projectEnvironments).where(eq(projectEnvironments.projectId, access.project.id)).orderBy(asc(projectEnvironments.name)); const environmentIds = items.map((item) => item.id); const counts = environmentIds.length ? await db.select({ environmentId: environmentVariables.environmentId, total: count() }).from(environmentVariables).where(inArray(environmentVariables.environmentId, environmentIds)).groupBy(environmentVariables.environmentId) : []; return c.json(items.map((item) => ({ ...item, variableCount: counts.find((count) => count.environmentId === item.id)?.total ?? 0 }))); });
routes.post("/:orgSlug/projects/:projectId/environments", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId"), "projects.manage_environments"); if (!access) return c.json({ error: "Project not found or access denied" }, 404); if (access.project.status === "archived") return c.json({ error: "Archived projects cannot receive new environments" }, 409); const parsed = environmentInput.safeParse(await c.req.json()); if (!parsed.success) return c.json({ error: "Invalid environment" }, 400); const id = crypto.randomUUID(); try { await db.insert(projectEnvironments).values({ id, organizationId: access.organization.id, projectId: access.project.id, ...parsed.data, slug: parsed.data.name }); await db.insert(auditLogs).values({ id: crypto.randomUUID(), actorId: access.userId, action: "environment.created", targetType: "environment", targetId: id, metadata: JSON.stringify({ projectId: access.project.id, slug: parsed.data.name }) }); return c.json({ id, ...parsed.data, slug: parsed.data.name }, 201); } catch (error) { if ((error as { code?: string }).code === "23505") return c.json({ error: "Environment slug already exists" }, 409); throw error; } });
routes.patch("/:orgSlug/projects/:projectId/environments/:environmentId", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId"), "projects.manage_environments"); if (!access) return c.json({ error: "Project not found or access denied" }, 404); const environment = await environmentInScope(access.project.id, c.req.param("environmentId")); if (!environment) return c.json({ error: "Environment not found" }, 404); const parsed = environmentUpdate.safeParse(await c.req.json()); if (!parsed.success) return c.json({ error: "Invalid environment" }, 400); const values = { ...parsed.data, ...(parsed.data.name ? { slug: parsed.data.name } : {}) }; try { const [updated] = await db.update(projectEnvironments).set(values).where(eq(projectEnvironments.id, environment.id)).returning(); await db.insert(auditLogs).values({ id: crypto.randomUUID(), actorId: access.userId, action: "environment.updated", targetType: "environment", targetId: environment.id, metadata: JSON.stringify({ projectId: access.project.id, fields: Object.keys(values) }) }); return c.json(updated); } catch (error) { if ((error as { code?: string }).code === "23505") return c.json({ error: "Environment slug already exists" }, 409); throw error; } });
routes.delete("/:orgSlug/projects/:projectId/environments/:environmentId", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId"), "projects.manage_environments"); if (!access) return c.json({ error: "Project not found or access denied" }, 404); const environment = await environmentInScope(access.project.id, c.req.param("environmentId")); if (!environment) return c.json({ error: "Environment not found" }, 404); if (environment.protected) return c.json({ error: "Protected environments cannot be deleted" }, 409); if (access.project.defaultEnvironmentId === environment.id) return c.json({ error: "Set another default environment before deleting this one" }, 409); const [removed] = await db.delete(projectEnvironments).where(eq(projectEnvironments.id, environment.id)).returning({ id: projectEnvironments.id }); await db.insert(auditLogs).values({ id: crypto.randomUUID(), actorId: access.userId, action: "environment.deleted", targetType: "environment", targetId: environment.id, metadata: JSON.stringify({ projectId: access.project.id }) }); return removed ? c.body(null, 204) : c.json({ error: "Environment not found" }, 404); });
routes.get("/:orgSlug/projects/:projectId/environments/:environmentId", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId")); if (!access) return c.json({ error: "Project not found or access denied" }, 404); const item = await environmentInScope(access.project.id, c.req.param("environmentId")); return item ? c.json(item) : c.json({ error: "Environment not found" }, 404); });
routes.get("/:orgSlug/projects/:projectId/environments/:environmentId/variables", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId")); if (!access) return c.json({ error: "Project not found or access denied" }, 404); const environment = await environmentInScope(access.project.id, c.req.param("environmentId")); if (!environment) return c.json({ error: "Environment not found" }, 404); const canReadSecretMetadata = access.permissions.includes("secrets.read_metadata"); const values = (await db.select().from(environmentVariables).where(eq(environmentVariables.environmentId, environment.id)).orderBy(asc(environmentVariables.key))).filter((item) => !item.isSecret || canReadSecretMetadata); return c.json(await Promise.all(values.map(async (item) => ({ id: item.id, key: item.key, isSecret: item.isSecret, value: item.isSecret ? null : await decryptEnvironmentValue(item.valueEncrypted), updatedAt: item.updatedAt })))); });
routes.put("/:orgSlug/projects/:projectId/environments/:environmentId/variables/:key", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId")); if (!access) return c.json({ error: "Project not found or access denied" }, 404); if (!access.permissions.includes("projects.update")) return c.json({ error: "Permission required: projects.update" }, 403); const environment = await environmentInScope(access.project.id, c.req.param("environmentId")); if (!environment) return c.json({ error: "Environment not found" }, 404); const parsed = variableInput.safeParse({ ...(await c.req.json()), key: c.req.param("key") }); if (!parsed.success) return c.json({ error: "Invalid environment variable" }, 400); const encrypted = await encryptEnvironmentValue(parsed.data.value); const existing = await db.query.environmentVariables.findFirst({ where: and(eq(environmentVariables.environmentId, environment.id), eq(environmentVariables.key, parsed.data.key)) }); const values = { key: parsed.data.key, valueEncrypted: encrypted, isSecret: parsed.data.isSecret }; if (existing) await db.update(environmentVariables).set(values).where(eq(environmentVariables.id, existing.id)); else await db.insert(environmentVariables).values({ id: crypto.randomUUID(), environmentId: environment.id, ...values }); return c.json({ key: parsed.data.key, isSecret: parsed.data.isSecret, value: parsed.data.isSecret ? null : parsed.data.value }); });
routes.delete("/:orgSlug/projects/:projectId/environments/:environmentId/variables/:key", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId")); if (!access) return c.json({ error: "Project not found or access denied" }, 404); if (!access.permissions.includes("projects.update")) return c.json({ error: "Permission required: projects.update" }, 403); const environment = await environmentInScope(access.project.id, c.req.param("environmentId")); if (!environment) return c.json({ error: "Environment not found" }, 404); const [removed] = await db.delete(environmentVariables).where(and(eq(environmentVariables.environmentId, environment.id), eq(environmentVariables.key, c.req.param("key")))).returning({ id: environmentVariables.id }); return removed ? c.body(null, 204) : c.json({ error: "Environment variable not found" }, 404); });
export { routes as environmentRoutes };
