import { db, environmentVariables, member, organization, projectEnvironments, projects } from "@repo/db";
import { and, asc, eq } from "drizzle-orm";
import { Hono } from "hono";
import { z } from "zod";
import { auth } from "../features/auth/config.js";
import { requireAuthenticatedUser } from "../middleware/auth.js";
import type { AppEnv } from "../types/env.js";

const routes = new Hono<AppEnv>();
routes.use("/*", requireAuthenticatedUser);
const environmentInput = z.object({ name: z.string().trim().regex(/^[a-z][a-z0-9-]{0,62}$/), displayName: z.string().trim().min(1).max(80), branch: z.string().trim().min(1).max(255).default("main"), autoDeployEnabled: z.boolean().default(false) });
const variableInput = z.object({ key: z.string().trim().regex(/^[A-Z_][A-Z0-9_]{0,127}$/), value: z.string().max(16_384), isSecret: z.boolean().default(false) });

async function scope(request: Request, slug: string, projectId: string) {
  const session = await auth.api.getSession({ headers: request.headers }); if (!session) return null;
  const org = await db.query.organization.findFirst({ where: eq(organization.slug, slug) }); if (!org) return null;
  const membership = await db.query.member.findFirst({ where: and(eq(member.organizationId, org.id), eq(member.userId, session.user.id)) }); if (!membership) return null;
  const project = await db.query.projects.findFirst({ where: and(eq(projects.id, projectId), eq(projects.organizationId, org.id)) });
  return project ? { org, project, userId: session.user.id, role: membership.role } : null;
}
function canManage(role: string) { return role === "owner" || role === "admin"; }
async function encryptionKey() {
  const secret = process.env.ENVIRONMENT_SECRET_ENCRYPTION_KEY ?? process.env.BETTER_AUTH_SECRET;
  if (!secret) throw new Error("Environment secret encryption key is not configured");
  return crypto.subtle.importKey("raw", await crypto.subtle.digest("SHA-256", new TextEncoder().encode(secret)), "AES-GCM", false, ["encrypt", "decrypt"]);
}
async function encrypt(value: string) { const iv = crypto.getRandomValues(new Uint8Array(12)); const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, await encryptionKey(), new TextEncoder().encode(value)); return `${Buffer.from(iv).toString("base64url")}.${Buffer.from(ciphertext).toString("base64url")}`; }
async function decrypt(value: string) { const [iv, ciphertext] = value.split("."); if (!iv || !ciphertext) throw new Error("Invalid encrypted environment variable"); const clear = await crypto.subtle.decrypt({ name: "AES-GCM", iv: Buffer.from(iv, "base64url") }, await encryptionKey(), Buffer.from(ciphertext, "base64url")); return new TextDecoder().decode(clear); }
async function environmentInScope(projectId: string, environmentId: string) { return db.query.projectEnvironments.findFirst({ where: and(eq(projectEnvironments.id, environmentId), eq(projectEnvironments.projectId, projectId)) }); }

routes.get("/:orgSlug/projects/:projectId/environments", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId")); if (!access) return c.json({ error: "Project not found or access denied" }, 404); const items = await db.select().from(projectEnvironments).where(eq(projectEnvironments.projectId, access.project.id)).orderBy(asc(projectEnvironments.name)); return c.json(await Promise.all(items.map(async (item) => ({ ...item, variableCount: (await db.select({ id: environmentVariables.id }).from(environmentVariables).where(eq(environmentVariables.environmentId, item.id))).length })))); });
routes.post("/:orgSlug/projects/:projectId/environments", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId")); if (!access) return c.json({ error: "Project not found or access denied" }, 404); if (!canManage(access.role)) return c.json({ error: "Owner or admin role required" }, 403); const parsed = environmentInput.safeParse(await c.req.json()); if (!parsed.success) return c.json({ error: "Invalid environment" }, 400); const id = crypto.randomUUID(); try { await db.insert(projectEnvironments).values({ id, organizationId: access.org.id, projectId: access.project.id, ...parsed.data }); return c.json({ id, ...parsed.data }, 201); } catch (error) { if ((error as { code?: string }).code === "23505") return c.json({ error: "Environment name already exists" }, 409); throw error; } });
routes.get("/:orgSlug/projects/:projectId/environments/:environmentId", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId")); if (!access) return c.json({ error: "Project not found or access denied" }, 404); const item = await environmentInScope(access.project.id, c.req.param("environmentId")); return item ? c.json(item) : c.json({ error: "Environment not found" }, 404); });
routes.get("/:orgSlug/projects/:projectId/environments/:environmentId/variables", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId")); if (!access) return c.json({ error: "Project not found or access denied" }, 404); const environment = await environmentInScope(access.project.id, c.req.param("environmentId")); if (!environment) return c.json({ error: "Environment not found" }, 404); const values = await db.select().from(environmentVariables).where(eq(environmentVariables.environmentId, environment.id)).orderBy(asc(environmentVariables.key)); return c.json(await Promise.all(values.map(async (item) => ({ id: item.id, key: item.key, isSecret: item.isSecret, value: item.isSecret ? null : await decrypt(item.valueEncrypted), updatedAt: item.updatedAt })))); });
routes.put("/:orgSlug/projects/:projectId/environments/:environmentId/variables/:key", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId")); if (!access) return c.json({ error: "Project not found or access denied" }, 404); if (!canManage(access.role)) return c.json({ error: "Owner or admin role required" }, 403); const environment = await environmentInScope(access.project.id, c.req.param("environmentId")); if (!environment) return c.json({ error: "Environment not found" }, 404); const parsed = variableInput.safeParse({ ...(await c.req.json()), key: c.req.param("key") }); if (!parsed.success) return c.json({ error: "Invalid environment variable" }, 400); const encrypted = await encrypt(parsed.data.value); const existing = await db.query.environmentVariables.findFirst({ where: and(eq(environmentVariables.environmentId, environment.id), eq(environmentVariables.key, parsed.data.key)) }); const values = { key: parsed.data.key, valueEncrypted: encrypted, isSecret: parsed.data.isSecret }; if (existing) await db.update(environmentVariables).set(values).where(eq(environmentVariables.id, existing.id)); else await db.insert(environmentVariables).values({ id: crypto.randomUUID(), environmentId: environment.id, ...values }); return c.json({ key: parsed.data.key, isSecret: parsed.data.isSecret, value: parsed.data.isSecret ? null : parsed.data.value }); });
routes.delete("/:orgSlug/projects/:projectId/environments/:environmentId/variables/:key", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug"), c.req.param("projectId")); if (!access) return c.json({ error: "Project not found or access denied" }, 404); if (!canManage(access.role)) return c.json({ error: "Owner or admin role required" }, 403); const environment = await environmentInScope(access.project.id, c.req.param("environmentId")); if (!environment) return c.json({ error: "Environment not found" }, 404); const [removed] = await db.delete(environmentVariables).where(and(eq(environmentVariables.environmentId, environment.id), eq(environmentVariables.key, c.req.param("key")))).returning({ id: environmentVariables.id }); return removed ? c.body(null, 204) : c.json({ error: "Environment variable not found" }, 404); });
export { routes as environmentRoutes };
