import { db, gameServers, member, organization } from "@repo/db";
import { and, asc, eq } from "drizzle-orm";
import { Hono } from "hono";
import { z } from "zod";
import { auth } from "../features/auth/config.js";
import { ApplicationRuntime } from "../lib/hosting/application-runtime.js";
import { requireAuthenticatedUser } from "../middleware/auth.js";
import type { AppEnv } from "../types/env.js";
const routes = new Hono<AppEnv>(); routes.use("/*", requireAuthenticatedUser); const runtime = new ApplicationRuntime();
const input = z.object({ name: z.string().trim().min(2).max(80), game: z.literal("minecraft-java"), version: z.string().trim().min(1).max(64).default("LATEST"), memoryMib: z.number().int().min(1024).max(16_384).default(2048) });
async function scope(request: Request, slug: string) { const session = await auth.api.getSession({ headers: request.headers }); if (!session) return null; const org = await db.query.organization.findFirst({ where: eq(organization.slug, slug) }); if (!org) return null; const membership = await db.query.member.findFirst({ where: and(eq(member.organizationId, org.id), eq(member.userId, session.user.id)) }); return membership ? { org, role: membership.role, userId: session.user.id } : null; }
const manager = (role: string) => role === "owner" || role === "admin";
routes.get("/:orgSlug/game-servers", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug")); if (!access) return c.json({ error: "Not found" }, 404); const servers = await db.select().from(gameServers).where(eq(gameServers.organizationId, access.org.id)).orderBy(asc(gameServers.name)); return c.json(await Promise.all(servers.map(async (server) => ({ ...server, ...(await runtime.gameStatus(server.containerName)) })))); });
routes.post("/:orgSlug/game-servers", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug")); if (!access) return c.json({ error: "Not found" }, 404); if (!manager(access.role)) return c.json({ error: "Owner or admin role required" }, 403); const parsed = input.safeParse(await c.req.json()); if (!parsed.success) return c.json({ error: "Invalid game server configuration" }, 400); const id = crypto.randomUUID(); const containerName = `devion-game-${id.replaceAll("-", "")}`; try { const state = await runtime.deployMinecraft({ containerName, ...parsed.data, labels: { "devion.organization-id": access.org.id, "devion.game-server-id": id } }); await db.insert(gameServers).values({ id, organizationId: access.org.id, createdByUserId: access.userId, containerName, status: state.status as "running" | "stopped" | "failed", ...parsed.data }); return c.json({ id, ...parsed.data, ...state }, 201); } catch (error) { c.get("logger").error({ error, containerName }, "Game server provisioning failed"); return c.json({ error: "Game server provisioning failed" }, 503); } });
routes.post("/:orgSlug/game-servers/:serverId/stop", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug")); if (!access) return c.json({ error: "Not found" }, 404); if (!manager(access.role)) return c.json({ error: "Owner or admin role required" }, 403); const server = await db.query.gameServers.findFirst({ where: and(eq(gameServers.id, c.req.param("serverId")), eq(gameServers.organizationId, access.org.id)) }); if (!server) return c.json({ error: "Game server not found" }, 404); await runtime.stop(server.containerName); await db.update(gameServers).set({ status: "stopped" }).where(eq(gameServers.id, server.id)); return c.json({ status: "stopped" }); });
routes.delete("/:orgSlug/game-servers/:serverId", async (c) => { const access = await scope(c.req.raw, c.req.param("orgSlug")); if (!access) return c.json({ error: "Not found" }, 404); if (!manager(access.role)) return c.json({ error: "Owner or admin role required" }, 403); const server = await db.query.gameServers.findFirst({ where: and(eq(gameServers.id, c.req.param("serverId")), eq(gameServers.organizationId, access.org.id)) }); if (!server) return c.json({ error: "Game server not found" }, 404); await runtime.remove(server.containerName); await db.delete(gameServers).where(eq(gameServers.id, server.id)); return c.body(null, 204); });
export { routes as gameServerRoutes };
