import { db, personalNotifications, personalTasks } from "@repo/db";
import { and, desc, eq } from "drizzle-orm";
import { Hono } from "hono";
import { z } from "zod";
import { auth } from "../features/auth/config.js";
import { requireAuthenticatedUser } from "../middleware/auth.js";
import type { AppEnv } from "../types/env.js";
const routes = new Hono<AppEnv>(); routes.use("/*", requireAuthenticatedUser);
const taskInput = z.object({ title: z.string().trim().min(1).max(160), description: z.string().max(2000).optional(), status: z.enum(["new", "in_progress", "waiting", "done", "archived"]).optional(), priority: z.enum(["low", "normal", "high", "urgent"]).optional() });
async function session(request: Request) { return auth.api.getSession({ headers: request.headers }); }
routes.get("/tasks", async c => { const current = await session(c.req.raw); if (!current) return c.json({ error: "Unauthorized" }, 401); return c.json(await db.select().from(personalTasks).where(eq(personalTasks.userId, current.user.id)).orderBy(desc(personalTasks.updatedAt))); });
routes.post("/tasks", async c => { const current = await session(c.req.raw); const data = taskInput.safeParse(await c.req.json()); if (!current || !data.success) return c.json({ error: "Invalid task" }, 400); const [item] = await db.insert(personalTasks).values({ id: crypto.randomUUID(), userId: current.user.id, ...data.data }).returning(); return c.json(item, 201); });
routes.patch("/tasks/:id", async c => { const current = await session(c.req.raw); const data = taskInput.partial().safeParse(await c.req.json()); if (!current || !data.success) return c.json({ error: "Invalid task" }, 400); const [item] = await db.update(personalTasks).set(data.data).where(and(eq(personalTasks.id, c.req.param("id")), eq(personalTasks.userId, current.user.id))).returning(); return item ? c.json(item) : c.json({ error: "Not found" }, 404); });
routes.delete("/tasks/:id", async c => { const current = await session(c.req.raw); if (!current) return c.json({ error: "Unauthorized" }, 401); await db.delete(personalTasks).where(and(eq(personalTasks.id, c.req.param("id")), eq(personalTasks.userId, current.user.id))); return c.body(null, 204); });
routes.get("/notifications", async c => { const current = await session(c.req.raw); if (!current) return c.json({ error: "Unauthorized" }, 401); return c.json(await db.select().from(personalNotifications).where(eq(personalNotifications.userId, current.user.id)).orderBy(desc(personalNotifications.createdAt))); });
routes.get("/summary", async c => { const current = await session(c.req.raw); if (!current) return c.json({ error: "Unauthorized" }, 401); const [tasks, notifications] = await Promise.all([db.select({ status: personalTasks.status }).from(personalTasks).where(eq(personalTasks.userId, current.user.id)), db.select({ isRead: personalNotifications.isRead }).from(personalNotifications).where(eq(personalNotifications.userId, current.user.id))]); return c.json({ tasks: tasks.length, openTasks: tasks.filter(item => item.status !== "done" && item.status !== "archived").length, completedTasks: tasks.filter(item => item.status === "done").length, unreadNotifications: notifications.filter(item => !item.isRead).length }); });
routes.patch("/notifications/:id/read", async c => { const current = await session(c.req.raw); if (!current) return c.json({ error: "Unauthorized" }, 401); const [item] = await db.update(personalNotifications).set({ isRead: true }).where(and(eq(personalNotifications.id, c.req.param("id")), eq(personalNotifications.userId, current.user.id))).returning(); return item ? c.json(item) : c.json({ error: "Not found" }, 404); });
export { routes as personalRoutes };
