"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, ArchiveRestore, Trash2 } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { useState } from "react";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
type Project = { name: string; status: "active" | "archived"; permissions: string[] };
const api = (path: string) => `${process.env.NEXT_PUBLIC_API_URL ?? ""}${path}`;
export default function ProjectSettingsDangerZonePage() {
  const { orgSlug, projectId } = useParams<{ orgSlug: string; projectId: string }>(); const router = useRouter(); const client = useQueryClient(); const [confirm, setConfirm] = useState("");
  const project = useQuery<Project>({ queryKey: ["orgs", orgSlug, "projects", projectId], queryFn: async () => { const response = await fetch(api(`/organizations/${orgSlug}/projects/${projectId}`), { credentials: "include" }); if (!response.ok) throw new Error("Projekt konnte nicht geladen werden"); return response.json(); } });
  const refresh = () => void client.invalidateQueries({ queryKey: ["orgs", orgSlug, "projects", projectId] });
  const archive = useMutation({ mutationFn: async (action: "archive" | "restore") => { const response = await fetch(api(`/organizations/${orgSlug}/projects/${projectId}/${action}`), { method: "POST", credentials: "include" }); if (!response.ok) throw new Error("Aktion konnte nicht ausgeführt werden"); }, onSuccess: refresh });
  const remove = useMutation({ mutationFn: async () => { const response = await fetch(api(`/organizations/${orgSlug}/projects/${projectId}`), { method: "DELETE", credentials: "include" }); if (!response.ok) { const body = await response.json().catch(() => null) as { error?: string; dependencies?: Record<string, number> } | null; const impact = body?.dependencies ? Object.entries(body.dependencies).filter(([, total]) => total > 0).map(([resource, total]) => `${total} ${resource}`).join(", ") : ""; throw new Error(impact ? `Löschen blockiert: ${impact}` : body?.error ?? "Löschen fehlgeschlagen"); } }, onSuccess: () => router.replace(`/${orgSlug}/projects`) });
  const name = project.data?.name ?? "";
  const canArchive = project.data?.permissions.includes("projects.archive") ?? false; const canDelete = project.data?.permissions.includes("projects.delete") ?? false;
  return <div className="space-y-6 p-6"><PageHeader title="Danger Zone" description="Archivierung ist reversibel; Löschen ist dauerhaft." />{project.isError ? <p role="alert" className="text-sm text-red-300">Projekt konnte nicht geladen werden.</p> : null}{canArchive ? <section className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-5"><p className="font-medium text-zinc-100">{project.data?.status === "archived" ? "Projekt wiederherstellen" : "Projekt archivieren"}</p><p className="mt-1 text-sm text-zinc-400">Archivierte Projects bleiben lesbar, akzeptieren aber keine neuen Applications oder Environments.</p><Button className="mt-4" variant="outline" disabled={!project.data || archive.isPending} onClick={() => archive.mutate(project.data?.status === "archived" ? "restore" : "archive")}><ArchiveRestore className="size-3.5" />{project.data?.status === "archived" ? "Wiederherstellen" : "Archivieren"}</Button></section> : null}{canDelete ? <section className="rounded-xl border border-red-400/20 bg-red-400/5 p-5"><div className="flex gap-3"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-red-400" /><div><p className="font-medium text-zinc-100">Projekt dauerhaft löschen</p><p className="mt-1 text-sm text-zinc-400">Löschen wird blockiert, solange Applications oder Domains existieren. Gib <span className="font-mono text-zinc-200">{name}</span> zur Bestätigung ein.</p><input value={confirm} onChange={(event) => setConfirm(event.target.value)} placeholder={name} className="mt-4 h-9 w-full max-w-xs rounded-lg border border-red-400/30 bg-red-400/5 px-3 text-sm text-zinc-100" />{remove.error ? <p role="alert" className="mt-2 text-sm text-red-300">{remove.error.message}</p> : null}<Button variant="destructive" size="sm" className="mt-3" disabled={!name || confirm !== name || remove.isPending} onClick={() => remove.mutate()}><Trash2 className="size-3.5" />{remove.isPending ? "Lösche …" : "Endgültig löschen"}</Button></div></div></section> : null}{project.data && !canArchive && !canDelete ? <p className="text-sm text-zinc-500">Du hast keine Berechtigung für Änderungen in der Danger Zone.</p> : null}</div>;
}
