providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    # Automatischer Redirect auf HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"